# Exported from Render on 2024-03-28T19:14:07Z
services:
- type: web
  name: EThread
  runtime: node
  repo: https://github.com/zee-ham-su/EThread
  branch: Master
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: MONGODB_URI
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
  rootDir: Thread/Api
version: "1"